
# # values.yaml should have cronjob.crons array of crawlers to run with schedule, name, id, etc.

# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   {{- /* initJobName changes every time the script runs. which forced existing jobs and pods to be deleted and thereby works around issue with helm upgrade refusing to modify existing job object */}}
#   name: "executiveOrdersSpider" #{{ include "app.ml.initJobName" . }}
# #   labels: {{- include "common.labels.standard" . | nindent 4 }}
# #     {{- if .Values.commonLabels }}
# #     {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
# #     {{- end }}
# #     app.kubernetes.io/component: ml
# #   {{- if .Values.commonAnnotations }}
# #   annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
# #   {{- end }}
# #   namespace: {{ .Release.Namespace }}
# spec:
#   schedule: "30 3 * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: "gamechanger-crawler"
#               image: "SOMEREGISTRY/advana/gamechanger/gamechanger-crawler"
#               imagePullPolicy: latest
#               command:
#               - /bin/sh
#               - -c
#               - scrapy runspider dataPipelines/gc_scrapy/gc_scrapy/spiders/executive_orders_spider.py \
#               - -a download_output_dir="{{/* CRAWLER_DATA_ROOT */}}" \
#               - -a previous_manifest_location="{{/* CRAWLER_DATA_ROOT */}}/prev-manifest.json" \
#               - -o "{{/* CRAWLER_DATA_ROOT */}}/output.json"
