crawler:
  # image - <Object>
  #   Main app image details - also used to run all jobs defined in .Values
  image:
    registry: ""
    repository: "advana/gamechanger/gamechanger-crawler"
    pullPolicy: Always
    tag: "latest"

  # replicaCount - <Integer >= 1>
  #   Number of app pod replicas to launch in the load-balancing group.
  #
  #   Tips:
  #   - when troubleshooting, set to 1 to avoid dealing with complications of load-balanced traffic
  replicaCount: 1

  updateStrategy:
    type: RollingUpdate
    
  defaultCronJobImage: 
    registry: ""
    repository: "advana/gamechanger/gamechanger-crawler"
    pullPolicy: Always
    tag: "latest"
  cronJobs:
    - name: "Crawler-Sunday"
      schedule: "1 1 * * 0"
      crawlerIDs: 
        - sorn_spider
        - secnav_spider
        - coast_guard_spider
        - omb_pubs_spider
        - dcma_spider
    - name: "Crawler-Monday"
      schedule: "1 1 * * 1"
      crawlerIDs:
        - legislation_spider
        - chief_national_guard_bureau_spider
        - ic_policies_spider
        - stig_spider
        - tradoc_spider
    - name: "Crawler-Tuesday"
      schedule: "1 1 * * 2"
      crawlerIDs:
        - army_pubs_spider
        - cfr_spider
        - us_code_spider
        - dha_spider
        - cnss_spider
    - name: "Crawler-Wednesday"
      schedule: "1 1 * * 3"
      crawlerIDs:
        - executive_orders_spider
        - fasab_spider
        - dod_coronavirus_spider
        - navy_med_spider
    - name: "Crawler-Thursday"
      schedule: "1 1 * * 4"
      crawlerIDs:
        - marine_corp_spider
        - milpersman_spider
        - bupers_spider
        - dfars_pgi_spider
    - name: "Crawler-Friday"
      schedule: "1 1 * * 5"
      crawlerIDs:
        - air_force_spider
        - nato_spider
        - navy_reserve_spider
        - jcs_pubs_spider
        - army_reserve_spider
    # saturday
    - name: "Crawler-Saturday"
      schedule: "1 1 * * 6"
      crawlerIDs:
        - dod_issuances_spider
        - dfar_subpart_regs_spider
        - fmr_spider
        - far_subpart_regs_spider
