apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.web.configMapName" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
data:
  GAMECHANGER_ELASTICSEARCH_HOST: {{ include "app.elasticsearch.host" . | quote }}
  GAMECHANGER_ELASTICSEARCH_PORT: {{ include "app.elasticsearch.port" . | quote }}
  EDA_ELASTICSEARCH_HOST: {{ include "app.elasticsearch.host" . | quote }}
  EDA_ELASTICSEARCH_PORT: {{ include "app.elasticsearch.port" . | quote }}
  POSTGRES_HOST_GAME_CHANGER: {{ include "app.postgresql.host" . | quote }}
  POSTGRES_HOST_GC_ORCHESTRATION: {{ include "app.postgresql.host" . | quote }}
  PG_HOST: {{ include "app.postgresql.host" . | quote }}
  PG_PORT: {{ include "app.postgresql.port" . | quote }}
  POSTGRES_HOST_UOT: {{ include "app.postgresql.host" . | quote }}
  REDIS_URL: "redis://{{ include "app.redis.host" . }}"
  GAMECHANGER_ML_API_HOST: {{ include "app.ml.host" . | quote }}
  NEO4J_URL: "neo4j://{{ include "app.neo4j.host" . }}"
  SAML_ISSUER: "{{ include "app.web.externalUrl" . }}"
  SAML_CALLBACK_URL: "{{ include "app.web.externalUrl" . }}/login/callback"
  REACT_APP_BACKEND_URL: "{{ include "app.web.externalUrl" . }}"
  REACT_APP_MEGA_MENU_ENDPOINT: "{{ include "app.web.externalUrl" . }}/api/gamechanger/megamenu/links"
  REACT_APP_USER_TOKEN_ENDPOINT: "{{ include "app.web.externalUrl" . }}/api/auth/token"
  REACT_APP_LOGIN_ROUTE: "{{ include "app.web.externalUrl" . }}/login"
