-- step 0: create dbs (idempotent)
CREATE DATABASE game_changer;
CREATE DATABASE "gc-orchestration";
-- CREATE DATABASE uot;
CREATE DATABASE uot WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';

-- step 1: execute sequelize on npm image
-- ignored here
-- step 2: something in python w/ datapipelines image?
-- ignored here
-- 
-- below all occurs in default postgres db?
-- 
\connect game_changer

INSERT INTO clone_meta (clone_name, search_module, export_module, "createdAt", "updatedAt", display_name, title_bar_module, navigation_module, card_module, is_live, url, permissions_required, clone_to_sipr, show_graph, show_tutorial, show_crowd_source, show_feedback, graph_module, main_view_module, available_at) VALUES ('gamechanger', 'policy/policySearchHandler', 'simple/simpleExportHandler', '2021-03-17 13:35:17.526000', '2021-03-17 13:35:19.927000', 'GAMECHANGER', 'policy/policyTitleBarHandler', 'policy/policyNavigationHandler', 'policy/policyCardHandler', true, 'gamechanger', false, false, true, true, true, true, 'policy/policyGraphHandler', 'policy/policyMainViewHandler', '{"all", "localhost"}') ON CONFLICT (clone_name) DO NOTHING;

INSERT INTO users ("user_id", cn, first_name, last_name, extra_fields, is_super_admin) VALUES (7890123456, 'TEST.TEST.T.7890123456' ,'TEST','TEST', '{"gamechanger": {"is_beta": true, "is_admin": true, "is_internal": true},  "clones_visited": ["gamechanger"]}', TRUE);

-- connect to uot db instead of default db
\connect uot

-- step 3: create_um_tables.sql
CREATE TABLE public.roles (
    id SERIAL,
    name text,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    owner character varying(255),
    application character varying(255),
    product character varying(255),
    sod_id character varying(255),
    description text,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.permissions (
    id SERIAL,
    name text,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL,
    username text NOT NULL,
    displayname text NOT NULL,
    lastlogin timestamp with time zone,
    sandbox_id integer,
    disabled boolean DEFAULT false,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    session_id text,
    email text,
    sub_agency text,
    extra_fields jsonb,
    PRIMARY KEY (id)
);

-- CREATE TABLE public.users (
--     id integer NOT NULL,
--     username text NOT NULL,
--     displayname text NOT NULL,
--     lastlogin timestamp with time zone,
--     sandbox_id integer,
--     disabled boolean DEFAULT false,
--     "createdAt" timestamp with time zone NOT NULL,
--     "updatedAt" timestamp with time zone NOT NULL,
--     session_id text,
--     email text,
--     sub_agency text,
--     extra_fields jsonb,
--     favorite_apps text[]
-- );

-- CREATE SEQUENCE public.users_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1;

-- ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


-- ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

-- ALTER TABLE ONLY public.users
--     ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- ALTER TABLE ONLY public.users
--     ADD CONSTRAINT users_username_key UNIQUE (username);


CREATE TABLE IF NOT EXISTS public.roleperms (
    id SERIAL,
    roleid integer NOT NULL,
    permissionid integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (roleid) REFERENCES public.roles (id)
);

CREATE TABLE IF NOT EXISTS public.userroles (
    id SERIAL,
    userid integer NOT NULL,
    roleid integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userid) REFERENCES public.users (id),
    FOREIGN KEY (roleid) REFERENCES public.roles (id)
);

-- step 4: pop_mini_RE.sql, this runs before the table is made so it doesnt work
truncate table responsibilities;

INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (0, 'DoDD S-5230.28.pdf', '(U) Policy for Low Observable (LO) and Counter Low Observable (CLO) Programs - THORN BAY', null, '• Contact the OPR below to obtain a copy.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (1, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', null, 'Develop policy and procedures to implement and manage the RD and FRD security program for access, dissemination, classification, declassification, and handling of RD and FRD information within the DoD in accordance with the Atomic Energy Act of 1954, as amended.', 'FRD|RD|Atomic Energy|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (2, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', null, 'Oversee DoD implementing policies and conduct on-site reviews for DoD Component security programs established in accordance with this Instruction.', 'DoD|DoD Component', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (3, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', 'In consultation with DOE: (1) Develop classification guides for programs over which both DoD and DOE have cognizance.', 'DoD|United States Department of Energy|DOE', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (4, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', '(2) Determine which information in the RD category relating primarily to the military utilization of nuclear weapons may be placed in the FRD category.', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (5, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', '(3) Prepare classification guides for FRD and RD relating primarily to the military utilization of nuclear weapons.', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (6, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', '(4) Declassify FRD information, relating primarily to the military utilization of nuclear weapons, which may be published without undue risk to the common defense and security.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (7, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', '(5) Prepare and maintain the list of DoD officials authorized to request access to RD data in the possession of DOE at Enclosure 4.', 'DoD|United States Department of Energy|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (8, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', 'Provide a copy of this list to DOE.', 'United States Department of Energy|DOE', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (9, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', 'b. Disseminate classification and declassification guides for RD and FRD information within the DoD.', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (10, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', 'c. Assist the DoD Components, when requested, in determining what information relating to the military utilization of nuclear weapons may be designated as FRD even if it has never been in the RD category.', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (11, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The DASD(NM), under the authority, direction, and control of the Under Secretary of Defense for Acquisition, Technology, and Logistics (through the Assistant Secretary of Defense for Nuclear, Chemical, and Biological Defense Programs (ASD(NCB))),', 'd. Provide information as necessary to the DOE Director of Classification to fulfill responsibilities under this section and section 1045.4 of Reference (d).', 'United States Department of Energy|section 1045.4 of Reference', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (12, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'Ensure that RD and FRD are classified in accordance with the policies in this Instruction and Reference (d).', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (13, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'Designate an RD management official to direct and administer the RD classification program within the DoD Component and whose duties ', 'Designate an RD management official to direct and administer the RD classification program within the DoD Component and whose duties shall include: (1) Dissemination of implementing directives and classification guides, as needed.', 'DoD Component|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (14, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Ensuring that U.S. Government and contractor personnel with access to RD and FRD are trained on the procedures for derivative classification, marking, recognizing, and handling RD and FRD information and documents.', 'FRD|RD|Rural Development|U.S. Government', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (15, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'c. Incorporate classification guidance into appropriate security classification guides relevant to their systems, programs, plans or projects, as appropriate.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (16, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'd. Assist the DASD(NM) with determining what information, to include RD and FRD relating primarily to the military utilization of nuclear weapons, may be placed in the FRD category.', 'FRD|RD|DASD(NM) |Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (17, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'e. Request changes or additions to the DoD List of Certifying Officials, as described in Enclosure 4, through the DASD(NM).', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (18, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'ACCESS a.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (19, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Have a valid DoD security clearance at a level commensurate with the information concerned.', 'DoD', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (20, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(1) The Secretary of Defense; the Deputy Secretary of Defense; the Secretaries of the Military Departments; the Chairman of the Joint Chiefs of Staff; the Under Secretaries of Defense; the Chairman, Nuclear Weapons Council; the Directors of the Defense Agencies; and their designees, are authorized to certify the need of DoD personnel, under their jurisdiction, to have access to RD in the possession of the DOE and other Federal agencies designated by the DOE.', 'DOE|Joint Chiefs of Staff|Nuclear Weapons Council|Military Departments|Rural Development|Defense|RD|Under Secretaries of Defense|DoD|United States Department of Energy|Defense Agencies', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (21, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(a) For the Navy and the Air Force, the authority to certify for RD access in the possession of DOE shall not be designated below the level of the authority granting the security clearance.', 'Air Force|DOE|United States Air Force|United States Navy|Navy|Rural Development|RD|United States Department of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (22, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) For the Army, the authority to certify for RD access shall not be designated below brigade level or equivalent.', 'Army|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (23, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(c) For contractor employees, the need for access to RD will, in all cases, be certified by a Government Contracting Officer.', 'RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (24, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Those persons listed in subparagraph 1.b.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (25, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', '(1) of this Enclosure, or their designees, ', '(1) of this Enclosure, or their designees, shall submit requests for access to RD through established security channels directly to: DoDI 5210.02, June 3, 2011 Change 2, 08/21/2018 ENCLOSURE 3 8 Department of Energy Director of Safeguards and Security Washington, DC 20545 (3) DoD requests for access to RD in the possession of Federal agencies other than DoD pertaining to the Army Research Reactor Program and the Navy Research Reactor Program shall be submitted to: U.S. Nuclear Regulatory Commission Division of Security Washington, DC 20555 (4) In situations other than specified in subparagraphs 1.b.', 'Navy Research Reactor Program|Safeguards|United States Navy|Washington|U.S. Nuclear Regulatory Commission Division|Rural Development|RD|DC|Office of Naval Research|DoD|Nuclear Regulatory Commission|Security Washington|Army Research Reactor Program', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (26, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) and 1.b.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (27, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) of this Enclosure, DoD requests for access to RD in the custody of DOE personnel shall be submitted to the DOE Headquarters Division having responsibility for the subject matter involved.', 'DOE Headquarters Division|DOE|Rural Development|RD|Enclosure|DoD|United States Department of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (28, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) When it is necessary for a DoD activity to establish authority for requesting access directly from DOE Managers of Operations, a request for such authority shall be submitted to the DOE Headquarters Division responsible for the program to which access is required.', 'DoD|United States Department of Energy|DOE Headquarters Division|DOE Managers of Operations', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (29, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(6) DOE has authorized its personnel to accept oral requests in emergencies.', 'United States Department of Energy|DOE', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (30, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(7) If an individual requires repeated access to the same type of information or continuing visits to a facility, under the cognizance of the same approving authority, the request shall so specify.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (31, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(1) At a minimum, the required security clearances for personnel eligible for access to CNWDI shall be final TOP SECRET or SECRET (as appropriate), or DOE “Q” for non-DoD personnel.', 'United States Department of Energy|DOE|Securities and Exchange Commission|CNWDI', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (32, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) U.S. citizenship is required, except in rare instances when an immigrant alien may possess a unique or very unusual talent or skill that is essential to the U.S. Government and not possessed to a comparable degree by an available U.S. citizen.', 'U.S.|U.S. Government', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (33, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) Written or oral communication of CNWDI shall be strictly limited to those personnel who have a need to know.', 'CNWDI', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (34, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) Personnel having a need for access to CNWDI shall be briefed on its sensitivity.', 'CNWDI', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (35, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) Documents or other media as defined in Reference (e), that contain CNWDI shall be clearly marked, “Critical Nuclear Weapons Design Information - DoD Instruction 5210.02 applies.” Similar documents published prior to the date of this Instruction will be similarly marked when they are withdrawn from files.', 'CNWDI|Critical Nuclear Weapons Design Information - DoD', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (36, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(6) Except for the special requirements enumerated in subparagraph 1.c.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (37, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) of this Enclosure, access to CNWDI within and between DoD Components, including DoD contractors, will be controlled in the same manner as other classified information in accordance with References (e) through (g).', 'DoD|CNWDI|DoD Components', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (38, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Valid need to know.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (39, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) Final TOP SECRET clearance based on a single scope background investigation or TOP SECRET “Q” for non-DoD personnel.', 'Securities and Exchange Commission', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (40, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) Access authorization does not imply need to know for all Sigma 14, Sigma 15, and Sigma 20 NWD.', 'NWD', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (41, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) Access authorization of Sigma 15 or Sigma 20 does not grant access to Sigma 14 NWD.', 'NWD', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (42, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Dissemination of RD information may be made to properly cleared DOE personnel and to DOE-cleared personnel of other Federal agencies.', 'United States Department of Energy|DOE|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (43, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) Dissemination of RD information pertaining only to nuclear research reactors or nuclear electric power generating reactors may be made to NRC personnel.', 'Nuclear Regulatory Commission|NRC|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (44, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) Dissemination of RD information other than that pertaining to aeronautical and space activities may be released to NASA personnel only through DOE.', 'National Aeronautics and Space Administration|DOE|Rural Development|NASA|United States Department of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (45, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) In all cases in subparagraphs 2.a.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (46, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(1) through 2.a.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (47, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) of this Enclosure, dissemination of RD information will be made only after the holder of the information has verified: (a) The identification of the prospective recipient.', 'RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (48, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) The validity of the prospective recipient’s clearance.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (49, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Except as provided in subparagraph 2.b.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (50, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(1) of this Enclosure, FRD will be treated and disseminated in the manner prescribed for classified information in Reference (e).', 'FRD|Enclosure', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (51, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) Verification of clearance, Sigma authorizations, and need to know must be verified for all participants prior to discussions.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (52, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) Sigma 14 documents shall be inventoried annually.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (53, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(a) Inventory results of Sigma 14 holdings will be reported annually to the DoD Use Control Program Coordinator (UCPC), ODASD(NM).', 'Control Program Coordinator|ODASD(NM) ', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (54, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) The ODASD(NM) UCPC will report Sigma 14 holdings to the National Nuclear Security Administration (NNSA) UCPC annually.', 'NNSA UCPC|National Nuclear Security Administration|ODASD(NM) UCPC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (55, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(c) Requests for transfer of Sigma 14 information outside of the NNSA require prior NNSA approval through the DoD UCPC, ODASD(NM).', 'National Nuclear Security Administration|NNSA|ODASD(NM) ', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (56, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) Storage requirements for classified material must be consistent with Reference (e), with the following additions for Sigma 14, Sigma 15, and Sigma 20 materials: (a) Sigma 14 documents must be physically separated by a separate safe or combination-protected safe drawer from non-Sigma 14 documents.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (57, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) Sigma 15 and Sigma 20 documents may be co-mingled with non-Sigma classified documents.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (58, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(c) Access to the safe containing Sigma 15 or Sigma 20 must be restricted to those who are authorized access to Sigma 15 or Sigma 20 information.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (59, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(d) Safes containing TOP SECRET Sigma 14 information must be located in a vault or vault-type room.', 'Securities and Exchange Commission', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (60, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) of this Enclosure.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (61, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) All RD and CNWDI files stored on shared and personal local drives shall be password-protected using the standard Microsoft Office file password protection protocol.', 'Rural Development|CNWDI|Microsoft Office', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (62, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) Websites posting RD and CNWDI information must ensure access is limited to authorized recipients by, at a minimum, a properly administered and protected individual identifier and password consistent with DoD Instruction 8500.01 (Reference (i)).', 'DoD Instruction|RD|CNWDI|Rural Development', ARRAY ['DoDI 8500.01']::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (63, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(4) Systems logons and properly configured screensavers are sufficient protection for e-mail files.', '4 Systems', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (64, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(5) Files contained on the SIPRNET are subject to Defense Information Systems Agency inspections to ensure compliance with this Instruction.', 'SIPRNET|Defense Information Systems Agency|Smithsonian Institution', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (65, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(6) Sigma 14, 15, and 20 information shall not be processed on the SIPRNET.', 'SIPRNET|Smithsonian Institution', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (66, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) SECRET is the classification level applied to information the unauthorized disclosure of which could reasonably be expected to cause serious damage to national security that the original classification authority is able to identify or describe.', 'Securities and Exchange Commission', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (67, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) CONFIDENTIAL is the classification level applied to information the unauthorized disclosure of which could reasonably be expected to cause damage to national security that the original classification authority is able to identify or describe.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (68, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) Production of SNM.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (69, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(c) Use of SNM in the Production of Energy.', 'Production of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (70, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) FRD describes classified information jointly determined by the DOE or its predecessor agencies and the DoD to be related primarily to the military utilization of atomic weapons and protected as NSI.', 'DOE|NSI|FRD|DoD|United States Department of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (71, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(b) Nuclear weapon safety and storage.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (72, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(c) Nuclear weapon yield and effects.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (73, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(d) Nuclear weapon storage and deployment locations.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (74, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', 'Handle as restricted Data in Foreign Dissemination Section 144.b, Atomic Energy Act of 1954 RESTRICTED DATA This document contains Restricted Data as defined in the Atomic Energy Act of 1954.', 'Data in Foreign Dissemination|Restricted Data|Atomic Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (75, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(1) Documents containing RD and FRD remain classified until a positive action by an authorized individual is taken within DOE for RD information and jointly by DoD-DOE for FRD or in accordance with joint DoD-DOE classification guides or DoD guides coordinated with DOE.', 'DOE|Rural Development|FRD|RD|DoD-DOE|DoD|United States Department of Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (76, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(2) In accordance with the Atomic Energy Act of 1954, as amended, and section 1045.38 of Reference (d), no date or event for automatic declassification will be applied to RD and FRD documents, even if such documents also contain NSI.', 'NSI|Rural Development|FRD|RD|Atomic Energy', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (77, 'DoDI 5210.02 CH 2.pdf', 'Access to and Dissemination of Restricted Data and Formerly Restricted Data', 'The Heads of DoD Components with access to RD and FRD', '(3) RD and FRD are exempt from all provisions of Reference (j) or its predecessor Executive orders, as amended, including automatic declassification.', 'FRD|RD|Rural Development', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (78, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, '(2) Ordering members of the RC to active duty with the consent of that member in accordance with section 12301(d) of Reference (d).', 'RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (79, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, '(d) Supersedes in part, to the extent that they are inconsistent with this instruction, Under Secretary of Defense for Personnel and Readiness (USD(P&R)) Memorandums (Reference (i) and (j)), with respect to accessing, utilizing, and managing RC forces.', 'Defense for Personnel and Readiness|RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (80, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, '(2) Coast Guard Reservists ordered to active duty by the Secretary of Homeland Security for emergency augmentation of regular Coast Guard forces during a serious natural or manmade disaster, accident, or catastrophe pursuant to section 712 of Title 14, USC (Reference (k)).', 'Homeland Security|Title 14|USC|Coast Guard', ARRAY ['Title 14']::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (81, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, '(3) National Guard members conducting Homeland Defense and Defense Support of Civil Authority operations pursuant to section 502(f) of Title 32, USC (Reference (l)).', 'United States National Guard|National Guard|Title 32|USC|Homeland Defense and Defense Support of Civil Authority', ARRAY ['Title 32']::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (82, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Use the procedures in this instruction to determine if activation with less than 30 days’ notice is warranted.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (83, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Establishes and oversees policies, plans, and programs for total force personnel and their allocation among the Military Departments and between the Active Components (AC) and the RCs.', 'AC|Active Components|Military Departments', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (84, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'b. Analyzes total force structure as it relates to military and civilian requirements, utilization, readiness, and support in accordance with Reference (a) and DoDD 1404.10 (Reference (p)) to ensure an appropriate mixture of ready personnel to execute the national defense strategy.', 'DoDD', ARRAY ['DoDD 1404.10']::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (85, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'c. Establishes policies concerning the alert, activation, and demobilization of RC members ordered to active duty.', 'RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (86, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'd. Reviews all activation requests that are: (1) Covered by the statutes listed in the involuntary activation category of Table 1 of Enclosure 3, referred to in this instruction as “involuntary activation authorities.” (2) Approved by the Secretaries of the Military Departments via the Secretary of Defense Notification Matrix of Service Secretary Approved Actions, referred to in this instruction as the “Notification Matrix.” e. Approves certain activation requests under involuntary activation authorities in accordance with paragraph 7d of Enclosure 3 of this instruction.', 'Defense Notification Matrix of Service Secretary Approved Actions|Military Departments', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (87, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'f. Reviews and forwards activation requests under involuntary activation authorities for Secretary of Defense decision via the Secretary of Defense Orders Book (SDOB) that do not meet approval criteria for the Secretaries of the Military Departments or the USD(P&R).', 'USD(P&R) |Military Departments|Defense Orders Book|Defense|SDOB', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (88, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'g. Advises the Secretary of Defense on all RC matters presented in the SDOB, the Notification Matrix, and on all requests for exception to the policies established by the Secretary of Defense or prescribed in this instruction.', 'Defense|SDOB|RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (89, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'h. Develops personnel and pay policies for RC members ordered to active duty in support of contingency operations, as defined in section 101(a) (13) of Reference (d).', 'RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (90, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Develops and oversees implementing policy, programs, and guidance for the activation, employment, and demobilization of the RC during periods of active duty in support of Military Service functions, operational missions, contingency operations, national emergency, times of war, or as otherwise authorized by law in accordance with DoDD 5125.01 (Reference (q)).', 'Military Service|DoDD|RC', ARRAY ['DoDD 5125.01']::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (91, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'c. Chairs the regularly scheduled Joint Mobilization Meeting (JMM), as described in section 1 of Enclosure 3. d. When directed, prepares any necessary documents for the Secretary of Defense to request additional RC access authority from the President or Congress.', 'RC|Defense|section 1 of Enclosure 3|Joint Mobilization Meeting|Congress', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (92, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Reviews and advises the USD(P&R) on actions under involuntary activation authorities submitted by the Military Services to the Notification Matrix or SDOB.', 'Military Services|SDOB|USD(P&R) ', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (93, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'c. Informs the Secretaries of the Military Departments and Commandant of the U.S. Coast Guard of USD(P&R) approval of Notification Matrix actions.', 'U.S. Coast Guard|Military Departments and Commandant of|USD(P&R) |Notification Matrix', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (94, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'd. Provides representation to the JMM.', 'JMM', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (95, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Advises the Secretary of Defense and the CJCS on RC forces necessary to implement national security and defense strategies.', 'Defense|RC', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (96, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'd. Provides representation to the JMM.', 'JMM', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (97, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'Develops and oversees implementation of plans and policies to ensure the DoD is prepared to perform homeland defense and defense support of civil authorities.', null, ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (98, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'c. Coordinates the use of DoD assistance to federal, State, and local officials in responding to threats involving chemical, biological, radiological, nuclear, and high-yield explosives weapons or related materials or technologies.', 'DoD|State', ARRAY []::text[]);
INSERT INTO public.responsibilities (id, "filename", "documentTitle", "organizationPersonnel", "responsibilityText", "otherOrganizationPersonnel", "documentsReferenced") VALUES (99, 'DoDI 1235.12 CH 1.pdf', 'Accessing the Reserve Components (RC)', null, 'd. Coordinates DoD assistance to lead federal departments and agencies in support of federal, State, and local officials in response to major disasters or emergencies in accordance with DoDD 3025.18 (Reference (v)) and DoDI 3025.21 (Reference (w)).', 'State|DoDD', ARRAY ['DoDD 3025.18', 'DoDI 3025.21']::text[]);

-- step 5: create_admins.sql
INSERT INTO admins (username) VALUES ('TEST.TEST.7890123456') ON CONFLICT DO NOTHING;

