{{- if .Values.ml.httpsProxy.enabled  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.ml.httpsProxy.configMapName" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    role: ml
    app.kubernetes.io/component: ml
data:
  nginx.conf: |
    daemon            off;
    user              nginx;
    master_process    on;
    worker_processes  1;
    
    error_log stderr info;

    events {
        worker_connections  1024;
    }

    http {
        upstream app {
          server  127.0.0.1:{{ default 5000 .Values.ml.service.ports.http }} max_fails=0;
        }

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /dev/stdout main;
        log_not_found off;

        keepalive_timeout  65;

        # Main App TLS Reverse Proxy
        server {
          listen {{ default 8443 .Values.ml.httpsProxy.containerPort }}       ssl;
          listen [::]:{{ default 8443 .Values.ml.httpsProxy.containerPort }}  ssl;

          server_name               default_server;
          ssl_certificate           {{ include "app.ml.tlsCert" . }};
          ssl_certificate_key       {{ include "app.ml.tlsCertKey" . }};
          # ssl_dhparam               /etc/nginx/tls/dhparam.pem;
          ssl_protocols             {{ default "TLSv1.2 TLSv1.3" .Values.ml.httpsProxy.sslProtocols }};
          ssl_ciphers               {{ default "HIGH:!aNULL:!eNULL:!MD5" .Values.ml.httpsProxy.sslCiphers }};
          ssl_prefer_server_ciphers on;

          ssl_session_cache         shared:SSL:40m;
          ssl_session_timeout       4h;
          ssl_session_tickets       on;

          add_header Strict-Transport-Security "max-age=31536000" always;

          gzip on;
          gzip_types *;
          gzip_proxied any;
          # proxy_buffer_size 8k;

          location / {
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto https;
            proxy_set_header    Host $http_host;
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_http_version  1.1;

            proxy_pass http://app/;
            proxy_redirect off;
          }
        }
    }
{{ end }}
