apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "app.ml.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: ml
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "app.ml.name" . }}
  replicas: {{ .Values.ml.replicaCount }}
  updateStrategy:
    type: {{ .Values.ml.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.ml.updateStrategy.type) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: ml
  template:
    metadata:
      annotations:
        deploy-ts: {{ now | quote }}
        checksum/configmap: {{ include (print $.Template.BasePath "/ml/configmap.yaml") . | sha256sum }}
        {{- if not .Values.ml.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/ml/secret.yaml") . | sha256sum }}
        {{- end}}
        {{- if and (not .Values.ml.tls.existingSecret) .Values.ml.tls.enabled }}
        checksum/tls-secret: {{ include (print $.Template.BasePath "/ml/tls-secret.yaml") . | sha256sum }}
        {{- end}}
        {{- if eq (include "app.elasticsearch.createSecret" .) "true" }}
        checksum/es-secret: {{ include (print $.Template.BasePath "/common/es-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.ml.podAnnotations -}}{{- toYaml . | nindent 8 }}{{- end }} 
      labels:   
      {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: ml
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "app.ml.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.ml.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if .Values.ml.tls.enabled }}
        - name: tls-secret-files
          secret:
            secretName: {{ include "app.ml.tlsSecretName" . | quote }}
        {{- end }}
      {{- if .Values.ml.init.container.enabled }}
      initContainers:
        - name: init-ml
          image: {{ template "app.ml.init.container.image" . }}
          {{- with .Values.ml.image.pullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          command: ["/bin/bash", "-c"]
          args: 
            - |
              {{- .Values.ml.init.container.script | trim | nindent 16 }}
          {{- with .Values.ml.appContainerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: 
          {{- if .Values.ml.persistence.enabled }}
            - name: {{ include "app.ml.pvcName" . }}
              mountPath: {{ .Values.ml.persistence.mountPath | quote }}
          {{- end }}
          env:
            - name: APP_VERSION
              value: {{ default "1.0.0" .Chart.AppVersion | quote }}
          {{- if .Values.ml.extraEnvVars }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVars "context" $ ) | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "app.ml.configMapName" .  | quote }}
            {{- if .Values.ml.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.ml.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ include "app.ml.name" . }}
          image: {{ template "app.ml.image" . }}
          {{- with .Values.ml.image.pullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          {{- with .Values.ml.startCommand }}
          command:
            {{- range . }}
            {{- printf "- %s" (. | quote) | nindent 12 }}
            {{- end -}}
          {{- end }}
          {{- with .Values.ml.appContainerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: 
          {{- if .Values.ml.persistence.enabled }}
            - name: {{ include "app.ml.pvcName" . }}
              mountPath: {{ .Values.ml.persistence.mountPath | quote }}
          {{- end }}
          env:
            - name: APP_VERSION
              value: {{ default "1.0.0" .Chart.AppVersion | quote }}
          {{- if .Values.elasticsearch.security.enabled }}
          {{- include "app.elasticsearch.security.envVars" . | nindent 12 }}
          {{- end }}
          {{- if .Values.ml.extraEnvVars }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVars "context" $ ) | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "app.ml.configMapName" .  | quote }}
            {{- if .Values.ml.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.ml.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" ( dict "value" .Values.ml.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ml.service.ports.http }}
            {{- if .Values.ml.tls.enabled }}
            - name: https
              containerPort: {{ .Values.ml.service.ports.https }}
              protocol: TCP
            {{- end }}
          {{- with .Values.ml.probes -}}{{- toYaml . | nindent 10}}{{- end }}
          {{- with .Values.ml.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if .Values.ml.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "app.ml.pvcName" . }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.ml.persistence.accessModes }}
      accessModes:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.ml.persistence.size | quote }}
      {{- with .Values.ml.persistence.storageClass }}
        storageClassName: {{ . }}
      {{- end }}
  {{- end }}
